FROM node:22-alpine AS build

WORKDIR /ui

COPY ui/package.json ui/package-lock.json ./
RUN npm ci

COPY ui/ ./
RUN npm run build


FROM nginx:1.27-alpine

COPY --from=build /ui/dist /usr/share/nginx/html

EXPOSE 80